In [1]:
import csv
import sys
import pickle as pkl
import pandas as pd
import random
import tqdm
import sklearn
import operator
from proposed_design_types import PROPOSED_DESIGN_TYPES

In [2]:
is_rct = lambda data: ['Randomized Controlled Trial' in ptyp_list for ptyp_list in data['ptyp']]
is_sr = lambda data: ['Systematic Review' in ptyp_list for ptyp_list in data['ptyp']]
is_casecontrol = lambda data: ['Case-Control Studies' in ptyp_list for ptyp_list in data['mesh']]
is_ct = lambda data: ['Clinical Trial' in ptyp_list for ptyp_list in data['ptyp']]
is_cohort = lambda data: ['Cohort Studies' in mesh_list for mesh_list in data['mesh']]
is_guideline = lambda data: ['Guideline' in ptyp_list for ptyp_list in data['ptyp']]
is_consensus = lambda data: ['Consensus' in ptyp_list for ptyp_list in data['mesh']]
is_qual = lambda data: ['Qualitative Research' in mesh_list for mesh_list in data['mesh']]
is_ctprotocol = lambda data: ['Clinical Trial Protocol' in ptyp_list for ptyp_list in data['ptyp']]

In [3]:
study_design_fns = ['is_rct',
'is_sr',
'is_casecontrol',
'is_ct',
'is_cohort',
'is_guideline',
'is_consensus',
'is_qual',
'is_ctprotocol']

In [4]:

filename_neg = '../data/pubmed_articles_neg.csv'

neg_data = pd.read_csv(
         filename_neg,
)

In [5]:
neg_data.columns

Index(['Unnamed: 0', 'pmid', 'status', 'indexing_method', 'title', 'abstract',
       'abstract_plaintext', 'authors', 'journal', 'journal_abbrv', 'year',
       'mesh', 'month', 'volume', 'issue', 'pages', 'ptyp', 'registry_ids',
       'dois'],
      dtype='object')

In [7]:
neg_data_human = neg_data[neg_data['indexing_method']== 'Human']

In [8]:
neg_data_human.columns

Index(['Unnamed: 0', 'pmid', 'status', 'indexing_method', 'title', 'abstract',
       'abstract_plaintext', 'authors', 'journal', 'journal_abbrv', 'year',
       'mesh', 'month', 'volume', 'issue', 'pages', 'ptyp', 'registry_ids',
       'dois'],
      dtype='object')

In [9]:
neg_data_human=neg_data_human.reset_index()

In [10]:
neg_data_human.to_csv('pubmed_articles_neg_human.csv')

# with open('pubmed_articles_neg_human.csv') as f_neg_human:

In [11]:
filename_pos_human = '../data/pubmed_articles_pos_human.csv'

# p = 0.2  # 20% of the lines
# keep the header, then take only 1% of lines
# if random from [0,1] interval is greater than 0.01 the row will be skipped
pos_data_human = pd.read_csv(
         filename_pos_human,
#          header=0, 
#          skiprows=lambda i: i>0 and random.random() > p
)

In [12]:
pos_data_human = pos_data_human.drop(columns='Unnamed: 0')

In [13]:
# pos_data_human.to_csv('pubmed_articles_pos_human.csv')

In [21]:
prop_typ_id_dict = {}

for fn in study_design_fns:
    prop_typ_id_dict[fn] = {}
    print(fn)
    pos_data_human_typ = pos_data_human[eval(fn)(pos_data_human)]
    prop_typ_id_dict[fn]['pos'] = list(pos_data_human_typ.index)
    print('pos', len(prop_typ_id_dict[fn]['pos']))
    not_fn = lambda data:  list(map(operator.not_, eval(fn)(data)))
    neg_data_human_typ = neg_data_human[ not_fn(neg_data_human)]
    prop_typ_id_dict[fn]['neg'] = list(neg_data_human_typ.index)
    print('neg', len(prop_typ_id_dict[fn]['neg']))
    print('neg/pos', len(prop_typ_id_dict[fn]['neg'])/len(prop_typ_id_dict[fn]['pos']))

is_rct
pos 489295
neg 5585042
neg/pos 11.414467754626555
is_sr
pos 121063
neg 5659292
neg/pos 46.74666908964754
is_casecontrol
pos 65790
neg 5628219
neg/pos 85.54824441404469
is_ct
pos 593277
neg 5564942
neg/pos 9.38000630396931
is_cohort
pos 78688
neg 5632460
neg/pos 71.57965636437577
is_guideline
pos 33826
neg 5676411
neg/pos 167.81206764027672
is_consensus
pos 10093
neg 5678494
neg/pos 562.6170613296345
is_qual
pos 7577
neg 5673091
neg/pos 748.7252210637455
is_ctprotocol
pos 3235
neg 5682702
neg/pos 1756.6312210200927

In [27]:
rct_ids = prop_typ_id_dict['is_rct']['pos']

In [29]:
18222648 in rct_ids

False

In [30]:
rct_ids

[30,
 34,
 37,
 59,
 98,
 103,
 193,
 230,
 238,
 265,
 275,
 297,
 324,
 326,
 328,
 332,
 361,
 378,
 391,
 396,
 436,
 440,
 578,
 579,
 595,
 675,
 731,
 767,
 820,
 822,
 870,
 871,
 885,
 896,
 898,
 951,
 959,
 975,
 989,
 990,
 992,
 993,
 1019,
 1047,
 1049,
 1064,
 1119,
 1122,
 1135,
 1173,
 1193,
 1209,
 1211,
 1212,
 1217,
 1232,
 1238,
 1240,
 1243,
 1266,
 1272,
 1274,
 1346,
 1349,
 1350,
 1357,
 1436,
 1440,
 1478,
 1482,
 1538,
 1541,
 1576,
 1580,
 1631,
 1636,
 1864,
 1886,
 1956,
 1971,
 1973,
 1982,
 1983,
 1984,
 1985,
 1986,
 2018,
 2066,
 2069,
 2070,
 2071,
 2072,
 2073,
 2075,
 2076,
 2079,
 2080,
 2081,
 2084,
 2085,
 2088,
 2109,
 2116,
 2124,
 2127,
 2221,
 2225,
 2239,
 2240,
 2257,
 2258,
 2317,
 2318,
 2319,
 2334,
 2335,
 2338,
 2357,
 2382,
 2387,
 2411,
 2431,
 2434,
 2445,
 2483,
 2545,
 2565,
 2575,
 2710,
 2731,
 2732,
 2733,
 2763,
 2788,
 2796,
 2804,
 2824,
 2831,
 2837,
 2845,
 2860,
 2862,
 2864,
 2865,
 2873,
 2886,
 2891,
 2895,
 2899,
 2912,
 2929,
 2930,
 2969,
 3087,
 3097,
 3105,
 3107,
 3108,
 3109,
 3126,
 3131,
 3134,
 3138,
 3236,
 3302,
 3320,
 3363,
 3395,
 3407,
 3408,
 3411,
 3413,
 3416,
 3449,
 3450,
 3490,
 3491,
 3502,
 3534,
 3588,
 3594,
 3595,
 3600,
 3644,
 3671,
 3696,
 3722,
 3734,
 3738,
 3744,
 3748,
 3783,
 3796,
 3798,
 3799,
 3800,
 3802,
 3804,
 3828,
 3837,
 3838,
 3847,
 3848,
 3874,
 3880,
 3898,
 3917,
 3920,
 3949,
 3962,
 3963,
 3985,
 4037,
 4038,
 4039,
 4105,
 4137,
 4147,
 4191,
 4194,
 4235,
 4239,
 4265,
 4266,
 4275,
 4359,
 4364,
 4366,
 4387,
 4395,
 4399,
 4422,
 4423,
 4427,
 4435,
 4437,
 4451,
 4456,
 4476,
 4477,
 4580,
 4601,
 4680,
 4696,
 4702,
 4721,
 4723,
 4725,
 4749,
 4762,
 4810,
 4824,
 4845,
 4853,
 4859,
 4863,
 4896,
 4897,
 4898,
 4923,
 4924,
 4927,
 4933,
 4950,
 4953,
 4956,
 5000,
 5022,
 5034,
 5055,
 5060,
 5078,
 5084,
 5088,
 5091,
 5097,
 5134,
 5179,
 5184,
 5196,
 5205,
 5206,
 5207,
 5218,
 5221,
 5222,
 5245,
 5267,
 5285,
 5290,
 5294,
 5316,
 5328,
 5354,
 5361,
 5367,
 5377,
 5499,
 5505,
 5519,
 5541,
 5543,
 5552,
 5553,
 5558,
 5578,
 5590,
 5605,
 5609,
 5610,
 5616,
 5624,
 5626,
 5653,
 5713,
 5795,
 5807,
 5812,
 5842,
 5843,
 5844,
 5859,
 5864,
 5865,
 5880,
 5881,
 5893,
 5894,
 5896,
 5905,
 5907,
 5924,
 5934,
 5949,
 5959,
 5960,
 5961,
 5962,
 5967,
 6004,
 6014,
 6054,
 6060,
 6066,
 6067,
 6093,
 6094,
 6095,
 6096,
 6133,
 6146,
 6163,
 6164,
 6182,
 6187,
 6273,
 6280,
 6286,
 6306,
 6315,
 6317,
 6332,
 6337,
 6397,
 6398,
 6399,
 6400,
 6401,
 6415,
 6418,
 6419,
 6449,
 6452,
 6456,
 6475,
 6501,
 6510,
 6511,
 6517,
 6528,
 6536,
 6556,
 6570,
 6571,
 6603,
 6612,
 6713,
 6715,
 6720,
 6735,
 6736,
 6767,
 6771,
 6781,
 6824,
 6827,
 6844,
 6850,
 6852,
 6904,
 6905,
 6908,
 6910,
 6911,
 6913,
 6916,
 6919,
 6966,
 6986,
 7019,
 7061,
 7062,
 7074,
 7095,
 7096,
 7098,
 7099,
 7101,
 7102,
 7150,
 7151,
 7178,
 7181,
 7184,
 7185,
 7209,
 7213,
 7244,
 7250,
 7256,
 7320,
 7330,
 7338,
 7342,
 7353,
 7354,
 7386,
 7387,
 7397,
 7421,
 7422,
 7432,
 7467,
 7472,
 7473,
 7506,
 7508,
 7509,
 7600,
 7605,
 7606,
 7607,
 7625,
 7628,
 7633,
 7638,
 7641,
 7643,
 7661,
 7673,
 7710,
 7721,
 7722,
 7758,
 7760,
 7791,
 7801,
 7803,
 7804,
 7808,
 7809,
 7810,
 7811,
 7868,
 7869,
 7872,
 7893,
 7982,
 7999,
 8051,
 8132,
 8143,
 8153,
 8160,
 8185,
 8230,
 8231,
 8239,
 8252,
 8276,
 8278,
 8300,
 8347,
 8371,
 8396,
 8414,
 8548,
 8557,
 8600,
 8622,
 8694,
 8810,
 8819,
 8827,
 8842,
 8845,
 8873,
 8874,
 8899,
 8902,
 8904,
 8907,
 8908,
 8952,
 8954,
 8965,
 8977,
 8985,
 8987,
 9025,
 9108,
 9110,
 9150,
 9158,
 9251,
 9289,
 9316,
 9354,
 9395,
 9488,
 9490,
 9538,
 9585,
 9586,
 9644,
 9663,
 9668,
 9701,
 9881,
 9912,
 9940,
 9941,
 9944,
 9945,
 10028,
 10029,
 10030,
 10031,
 10047,
 10078,
 10080,
 10081,
 10090,
 10091,
 10114,
 10115,
 10116,
 10190,
 10194,
 10197,
 10226,
 10227,
 10233,
 10278,
 10285,
 10365,
 10383,
 10384,
 10390,
 10391,
 10399,
 10401,
 10423,
 10425,
 10435,
 10436,
 10440,
 10442,
 10443,
 10444,
 10445,
 10446,
 10449,
 10504,
 10540,
 10558,
 10642,
 10643,
 10651,
 10652,
 10684,
 10731,
 10734,
 10798,
 10800,
 10802,
 10811,
 10812,
 10825,
 10827,
 10846,
 10884,
 10889,
 10890,
 10895,
 10904,
 11026,
 11030,
 11053,
 11108,
 11109,
 11115,
 11163,
 11183,
 11194,
 11216,
 11217,
 11218,
 11219,
 11238,
 11278,
 11366,
 11370,
 11469,
 11472,
 11476,
 11496,
 11509,
 11510,
 11549,
 11552,
 11609,
 11660,
 11691,
 11705,
 11741,
 11777,
 11795,
 11797,
 11799,
 11829,
 11830,
 11859,
 11869,
 11925,
 11937,
 11938,
 12004,
 12059,
 12071,
 12132,
 12306,
 12309,
 12328,
 12383,
 12390,
 12428,
 12435,
 12437,
 12438,
 12439,
 12471,
 12472,
 12474,
 12517,
 12537,
 12644,
 12715,
 12726,
 12759,
 12789,
 12792,
 12817,
 12823,
 12831,
 12833,
 12855,
 12856,
 12902,
 12909,
 12910,
 12992,
 12993,
 12994,
 13028,
 13074,
 13217,
 13220,
 13243,
 13296,
 13343,
 13353,
 13388,
 13409,
 13436,
 13554,
 13597,
 13598,
 13599,
 13600,
 13601,
 13669,
 13783,
 13784,
 13796,
 13797,
 13798,
 13799,
 13801,
 13814,
 13853,
 13854,
 13865,
 13966,
 13998,
 14021,
 14024,
 14115,
 14143,
 14215,
 14216,
 14238,
 14321,
 14329,
 14333,
 14334,
 14336,
 14337,
 14354,
 14356,
 14367,
 14369,
 14395,
 14415,
 14431,
 14450,
 14464,
 14483,
 14484,
 14492,
 14500,
 14504,
 14505,
 14506,
 14508,
 14518,
 14554,
 14561,
 14566,
 14567,
 14583,
 14586,
 14589,
 14594,
 14642,
 14650,
 14658,
 14665,
 14677,
 14692,
 14697,
 14722,
 14723,
 14734,
 14745,
 14751,
 14759,
 14781,
 14788,
 14789,
 14790,
 14791,
 14792,
 14793,
 14795,
 14817,
 14820,
 14843,
 14856,
 14863,
 14872,
 14880,
 14891,
 14892,
 14893,
 14896,
 14901,
 14907,
 14916,
 14917,
 14919,
 14920,
 14942,
 14971,
 14975,
 14976,
 14977,
 15059,
 15084,
 15087,
 15091,
 15142,
 15147,
 15153,
 15154,
 15157,
 15158,
 15159,
 15160,
 15197,
 15200,
 15224,
 15229,
 15269,
 15270,
 15280,
 15307,
 15322,
 15352,
 15419,
 15421,
 15454,
 15468,
 15470,
 15473,
 15493,
 15512,
 15513,
 15515,
 15517,
 15518,
 15522,
 15588,
 15613,
 15647,
 15658,
 15691,
 15702,
 15704,
 15727,
 15748,
 15769,
 15793,
 15799,
 15815,
 15821,
 15822,
 15823,
 15824,
 15844,
 15859,
 15876,
 15877,
 15878,
 15892,
 15905,
 15910,
 15932,
 15942,
 15943,
 15960,
 15966,
 15973,
 15989,
 15997,
 16012,
 16013,
 16021,
 16025,
 16039,
 16049,
 16054,
 16057,
 16062,
 16080,
 16083,
 16086,
 16087,
 16089,
 16096,
 16104,
 16106,
 16123,
 16131,
 16147,
 16205,
 16223,
 16266,
 16267,
 16271,
 16295,
 16305,
 16355,
 16365,
 16371,
 16391,
 16396,
 16399,
 16403,
 16409,
 16426,
 16433,
 16443,
 16444,
 16451,
 16452,
 16477,
 16478,
 16483,
 16487,
 16492,
 16500,
 16508,
 16533,
 16544,
 16588,
 16589,
 16601,
 16602,
 16603,
 16607,
 16620,
 16623,
 16642,
 16644,
 16645,
 16646,
 16676,
 16682,
 16688,
 16690,
 16725,
 16729,
 16732,
 16733,
 16734,
 16735,
 16738,
 16744,
 16759,
 16776,
 16782,
 16791,
 16816,
 16823,
 16825,
 16827,
 16830,
 16831,
 16855,
 16862,
 16874,
 16876,
 16891,
 16895,
 16898,
 16922,
 16931,
 16937,
 16940,
 16953,
 16957,
 16972,
 16978,
 16989,
 17008,
 17042,
 17049,
 17074,
 17083,
 17084,
 17086,
 17088,
 17097,
 17124,
 17125,
 17154,
 17157,
 17175,
 17176,
 17193,
 17207,
 17239,
 17261,
 17267,
 17278,
 17280,
 17302,
 17353,
 17364,
 17374,
 17380,
 17384,
 17422,
 17423,
 17450,
 17520,
 17533,
 17534,
 17556,
 ...]

In [ ]:
import pickle as pkl



with open('pos_neg_dataset_ids.pkl', 'wb') as f:
    pkl.dump(prop_typ_id_dict, f)

In [ ]:
neg_data_human_sr = neg_data_human[['Systematic Review' not in eval(ptyp) for ptyp in neg_data_human['ptyp']]]

In [ ]:
human_sr_neg = human_sr_neg.drop(columns = ['indexing_method', 'abstract', 'month', 'volume', 'issue', 'dois', 'ptyp', 'registry_ids', 'pages', 'Unnamed: 0'], inplace = True)

In [ ]:
human_sr_pos = pos_data[['Systematic Review' in eval(ptyp) for ptyp in pos_data['ptyp']]]

In [16]:
human_rct_pos = pos_data_human[['Randomized Controlled Trial' in eval(ptyp) for ptyp in pos_data_human['ptyp']]]

In [17]:
human_rct_pos.head()

,unnamed: 0,pmid,status,indexing_method,title,abstract,abstract_plaintext,authors,journal,journal_abbrv,year,mesh,month,volume,issue,pages,ptyp,registry_ids,dois
30,50,18222648,MEDLINE,Human,Neuropsychological predictors of functional ou...,"[{'header': '_UNSTRUCTURED', 'text': 'Cognitiv...",Cognitive Behavioral Social Skills Training (C...,"[{'Initials': 'E', 'LastName': 'Granholm', 'Fo...",Schizophrenia research,Schizophr Res,2008.0,"['Ambulatory Care', 'Antipsychotic Agents', 'C...",Mar,100,1-3,"{'page_from': '133', 'page_to': '143'}","['Comparative Study', 'Journal Article', 'Rand...",[],['10.1016/j.schres.2007.11.032']
34,72,18222671,MEDLINE,Human,Aescin and troxerutin as a successful combinat...,"[{'header': '_UNSTRUCTURED', 'text': 'A fixed ...",A fixed combination of aescin and troxerutin h...,"[{'Initials': 'CP', 'LastName': 'Siegers', 'Fo...",Phytomedicine : international journal of phyto...,Phytomedicine,2008.0,"['Administration, Oral', 'Aesculus', 'Aged', '...",Mar,15,3,"{'page_from': '160', 'page_to': '163'}","['Comparative Study', 'Journal Article', 'Rand...",[],['10.1016/j.phymed.2007.11.025']
37,83,18222683,MEDLINE,Human,Efficacy of formoterol Turbuhaler in the emerg...,"[{'header': '_UNSTRUCTURED', 'text': 'Dry powd...",Dry powder devices are rarely used in the emer...,"[{'Initials': 'KM', 'LastName': 'van den Broek...",Respiratory medicine,Respir Med,2008.0,"['Aged', 'Analysis of Variance', 'Area Under C...",Apr,102,4,"{'page_from': '579', 'page_to': '585'}","['Comparative Study', 'Journal Article', 'Rand...",[],['10.1016/j.rmed.2007.11.009']
59,133,18222735,MEDLINE,Human,Effects of goshuyuto on lateralization of pupi...,"[{'header': '_UNSTRUCTURED', 'text': 'Autonomi...",Autonomic nervous imbalance is implicated in c...,"[{'Initials': 'A', 'LastName': 'Wakasugi', 'Fo...",Autonomic neuroscience : basic & clinical,Auton Neurosci,2008.0,"['Adolescent', 'Adult', 'Aged', 'Child', 'Doub...",May,139,1-2,"{'page_from': '9', 'page_to': '14'}","['Clinical Trial', 'Comparative Study', 'Journ...",[],['10.1016/j.autneu.2007.12.002']
98,407,18223010,MEDLINE,Human,Effect of glycemic exposure on the risk of mic...,"[{'header': 'OBJECTIVE', 'text': 'The Diabetes...",OBJECTIVE\n\n\nThe Diabetes Control and Compli...,"[{'Initials': 'JM', 'LastName': 'Lachin', 'For...",Diabetes,Diabetes,2008.0,"['Adolescent', 'Adult', 'Biomarkers', 'Cohort ...",Apr,57,4,"{'page_from': '995', 'page_to': '991001'}","['Journal Article', 'Randomized Controlled Tri...",[],['10.2337/db07-1618']

In [58]:
human_sr_pos = human_sr_pos.drop(columns = ['indexing_method', 'abstract', 'month', 'volume', 'issue', 'dois', 'ptyp', 'registry_ids', 'pages', 'Unnamed: 0'])

In [60]:
human_sr_pos['label'] = 1

In [63]:
human_sr = pd.concat([human_sr_neg, human_sr_pos])

In [64]:
human_sr = human_sr.sample(frac=1, random_state=42)

In [65]:
human_sr

,pmid,status,title,abstract_plaintext,authors,journal,journal_abbrv,year,mesh,label
9533,1901457,MEDLINE,A novel metalloproteinase present in freshly i...,We have utilized [3H] gelatin to document high...,"[{'Initials': 'Q', 'LastName': 'Le', 'ForeName...",The American journal of physiology,Am J Physiol,1991,"['Animals', 'Cell Fractionation', 'Dithiothrei...",0
5121,18249490,MEDLINE,Effect of pH on phenol biosorption by marine s...,Biosorption of phenol by the marine seaweeds L...,"[{'Initials': 'AE', 'LastName': 'Navarro', 'Fo...",Journal of hazardous materials,J Hazard Mater,2008,"['Adsorption', 'Biomass', 'Hydrogen-Ion Concen...",0
10713,1907206,MEDLINE,"[Patient oriented, prospective comparative stu...",In a prospective cross-over study involving 30...,"[{'Initials': 'JW', 'LastName': 'Brandes', 'Fo...",Biomedizinische Technik. Biomedical engineering,Biomed Tech (Berl),1991,"['Adolescent', 'Adult', 'Aged', 'Enteral Nutri...",0
14181,18237457,MEDLINE,Effects of mindful and non-mindful exercises o...,PURPOSE\n\n\nAn emerging body of evidence has ...,"[{'Initials': 'HW', 'LastName': 'Tsang', 'Fore...",The British journal of clinical psychology,Br J Clin Psychol,2008,"['Adult', 'Aged', 'Breathing Exercises', 'Cont...",1
1390,18229890,MEDLINE,Host perception and signal transduction studie...,BACKGROUND\n\n\nQuinoxyfen is a potent and eff...,"[{'Initials': 'S', 'LastName': 'Lee', 'ForeNam...",Pest management science,Pest Manag Sci,2008,"['Ascomycota', 'Carboxylic Ester Hydrolases', ...",0
...,...,...,...,...,...,...,...,...,...,...
11573,1911560,MEDLINE,Some biophysical applications of motional cont...,The principal advantage of the n.m.r. imaging ...,"[{'Initials': 'PJ', 'LastName': 'Back', 'ForeN...",International journal of biological macromolec...,Int J Biol Macromol,1991,"['Animals', 'Biophysics', 'Caseins', 'Cattle',...",0
5452,18251175,MEDLINE,Rapamycin enhances the anti-tumor effect of ge...,BACKGROUND/AIMS\n\n\nRapamycin is a potent inh...,"[{'Initials': 'T', 'LastName': 'Okada', 'ForeN...",Hepato-gastroenterology,Hepatogastroenterology,2007,"['Antibiotics, Antineoplastic', 'Blotting, Wes...",0
5652,18252223,MEDLINE,Submicroscopic duplications of the hydroxyster...,Submicroscopic copy-number imbalances contribu...,"[{'Initials': 'G', 'LastName': 'Froyen', 'Fore...",American journal of human genetics,Am J Hum Genet,2008,"['3-Hydroxyacyl CoA Dehydrogenases', 'Base Seq...",0
967,18227740,MEDLINE,Obsessive-compulsive spectrum phenomena and th...,NaN,"[{'Initials': 'E', 'LastName': 'Hollander', 'F...",CNS spectrums,CNS Spectr,2008,['Diagnostic and Statistical Manual of Mental ...,0
7559,1891502,MEDLINE,[Refractory patient in Japanese psychiatry and...,NaN,"[{'Initials': 'K', 'LastName': 'Nakayama', 'Fo...",Seishin shinkeigaku zasshi = Psychiatria et ne...,Seishin Shinkeigaku Zasshi,1991,"['Crime', 'Criminal Law', 'Criminal Psychology...",0

In [14]:
sr_pos_ids = prop_typ_id_dict['is_sr']['pos']
sr_pos_set  = pos_data_human.loc[sr_pos_ids]

In [19]:
sr_neg_ids = prop_typ_id_dict['is_sr']['neg']
sr_neg_set  = neg_data_human.loc[sr_neg_ids]

In [18]:
len(neg_data_human)

5683273

In [19]:
len(sr_neg_ids)

5659292

In [28]:
pos_data_human

,Unnamed: 0,unnamed: 0,pmid,status,indexing_method,title,abstract,abstract_plaintext,authors,journal,journal_abbrv,year,mesh,month,volume,issue,pages,ptyp,registry_ids,dois
0,0,1,18222599,MEDLINE,Human,Laparoscopic versus open partial nephrectomy: ...,"[{'header': 'OBJECTIVES', 'text': 'To critical...",OBJECTIVES\n\n\nTo critically review the curre...,"[{'Initials': 'F', 'LastName': 'Porpiglia', 'F...",European urology,Eur Urol,2008.0,"['Carcinoma, Renal Cell', 'Clinical Competence...",Apr,53,4,{},"['Journal Article', 'Review']",[],['10.1016/j.eururo.2008.01.025']
1,1,3,18222601,MEDLINE,Human,Editorial comment on: expression and prognosti...,[],NaN,"[{'Initials': 'P', 'LastName': 'Härkönen', 'Fo...",European urology,Eur Urol,2008.0,"['Annexin A3', 'Humans', 'Male', 'Prognosis', ...",Dec,54,6,"{'page_from': '1322', 'page_to': '1322'}","['Comment', 'Editorial']",[],['10.1016/j.eururo.2008.01.002']
2,2,4,18222602,MEDLINE,Human,Editorial comment on: celecoxib has potent ant...,[],NaN,"[{'Initials': 'S', 'LastName': 'Brandau', 'For...",European urology,Eur Urol,2008.0,"['Animals', 'BCG Vaccine', 'Carcinoma, Transit...",Sep,54,3,"{'page_from': '629', 'page_to': '630'}","['Comment', 'Editorial']",[],['10.1016/j.eururo.2008.01.014']
3,3,5,18222603,MEDLINE,Human,Editorial comment on: expression and prognosti...,[],NaN,"[{'Initials': 'GJ', 'LastName': 'van Leenders'...",European urology,Eur Urol,2008.0,"['Annexin A3', 'Humans', 'Male', 'Microarray A...",Dec,54,6,"{'page_from': '1323', 'page_to': '1323'}","['Comment', 'Editorial']",[],['10.1016/j.eururo.2008.01.003']
4,4,6,18222604,MEDLINE,Human,Considerations on the use of urine markers for...,[],NaN,"[{'Initials': 'BW', 'LastName': 'van Rhijn', '...",European urology,Eur Urol,2008.0,"['Biomarkers, Tumor', 'Carcinoma, Transitional...",May,53,5,"{'page_from': '880', 'page_to': '881'}","['Comment', 'Editorial']",[],['10.1016/j.eururo.2008.01.043']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8584786,8584786,29982,24210460,MEDLINE,Human,Pregnancy-related knowledge and information ne...,"[{'header': '_UNSTRUCTURED', 'text': ""For wome...","For women with epilepsy (WWE), pregnancy is co...","[{'Initials': 'A', 'LastName': 'McGrath', 'For...",Epilepsy & behavior : E&B,Epilepsy Behav,2014.0,"['Anticonvulsants', 'Epilepsy', 'Female', 'Hea...",Feb,31,NaN,"{'page_from': '246', 'page_to': '255'}","['Journal Article', ""Research Support, Non-U.S...",[],['10.1016/j.yebeh.2013.09.044']
8584787,8584787,29984,24210462,MEDLINE,Human,Australia's seizure divide - indigenous versus...,"[{'header': '_UNSTRUCTURED', 'text': 'Indigeno...",Indigenous Australians suffer the highest mort...,"[{'Initials': 'C', 'LastName': 'Plummer', 'For...",Epilepsy & behavior : E&B,Epilepsy Behav,2014.0,"['Adolescent', 'Adult', 'Australia', 'Ethnic G...",Feb,31,NaN,"{'page_from': '363', 'page_to': '368'}","['Comparative Study', 'Journal Article', ""Rese...",[],['10.1016/j.yebeh.2013.09.042']
8584788,8584788,29986,24210464,MEDLINE,Human,Research on psychosocial aspects of epilepsy i...,"[{'header': '_UNSTRUCTURED', 'text': 'This stu...",This study reviewed research conducted on the ...,"[{'Initials': 'JM', 'LastName': 'Al-Khateeb', ...",Epilepsy & behavior : E&B,Epilepsy Behav,2014.0,"['Biomedical Research', 'Epilepsy', 'Health Kn...",Feb,31,NaN,"{'page_from': '256', 'page_to': '262'}","['Journal Article', 'Review']",[],['10.1016/j.yebeh.2013.09.033']
8584789,8584789,29989,24210468,MEDLINE,Human,Emerging methods for the fabrication of polyme...,"[{'header': '_UNSTRUCTURED', 'text': 'Hollow p...",Hollow polymer capsules are attracting increas...,"[{'Initials': 'J', 'LastName': 'Cui', 'ForeNam...",Advances in colloid and interface science,Adv Colloid Interface Sci,2014.0,"['Capsules', 'Chemical Phenomena', 'Drug Compo...",May,207,NaN,"{'page_from': '14', 'page_to': '31'}","['Journal Article', ""Research Support, Non-U.S...",[],['10.1016/j.cis.2013.10.012']
8584790,8584790,29993,24210465,MEDLINE,Human,Paranoid psychosis and cognitive impairment as...,"[{'header': 'OBJECTIVE', 'text': 'To report a ...",OBJECTIVE\n\n\nTo report a case of paranoid ps...,"[{'Initials': 'A', 'LastName': 'Budhram', 'For...",General hospital psychiatry,Gen Hosp Psychiatry,2014.0,"['Antiviral Agents', 'Cognition Disorders', 'D...",NaN,36,1,"{'page_from': '126.e3', 'page_to': '126.e5'}","['Case Reports', 'Journal Article']",[],['10.1016/j.genhosppsych.2013.10.008']