In [2]:
import pandas as pd

In [10]:
results_linear_pd = pd.read_json('results_titles_abstracts_linear.json')

In [11]:
results_linear_pd

,ptype,model_type,neg_to_pos_ratio,best_penalty,best_alpha,recall_val,spec_val,precision_val_even,f1_val_even,accuracy_val,recall_test,spec_test,precision_test_even,f1_test_even,accuracy_test
0,is_rct,hinge,1,elasticnet,1.000000e-05,0.90725,0.92175,0.920599,0.913876,0.914500,0.91125,0.91550,0.915139,0.913191,0.913375
1,is_rct,log,1,l1,2.976351e-06,0.89700,0.93150,0.929052,0.912745,0.914250,0.90250,0.92650,0.924693,0.913462,0.914500
2,is_rct,modified_huber,1,l2,2.636651e-07,0.88300,0.93150,0.928008,0.904945,0.907250,0.88200,0.92875,0.925256,0.903110,0.905375
3,is_rct,squared_hinge,1,l1,1.128838e-09,0.91775,0.90000,0.901744,0.909677,0.908875,0.91875,0.89650,0.898753,0.908641,0.907625
4,is_rct,perceptron,1,l2,2.069138e-09,0.90025,0.91675,0.915353,0.907739,0.908500,0.90175,0.91500,0.913859,0.907764,0.908375
5,is_sr,hinge,1,l1,1.000000e-05,0.98125,0.99075,0.990661,0.985933,0.986000,0.98625,0.99075,0.990708,0.988474,0.988500
6,is_sr,log,1,l1,1.000000e-05,0.98100,0.99175,0.991660,0.986301,0.986375,0.98650,0.99225,0.992205,0.989344,0.989375
7,is_sr,modified_huber,1,elasticnet,6.951928e-09,0.97525,0.98550,0.985350,0.980274,0.980375,0.98075,0.98875,0.988659,0.984689,0.984750
8,is_sr,squared_hinge,1,l1,3.359818e-10,0.98050,0.98200,0.981973,0.981236,0.981250,0.98475,0.98450,0.984504,0.984627,0.984625
9,is_sr,perceptron,1,l1,8.858668e-07,0.97600,0.98825,0.988104,0.982015,0.982125,0.97750,0.98950,0.989372,0.983400,0.983500
10,is_casecontrol,hinge,1,l2,5.455595e-06,0.84875,0.87650,0.872975,0.860692,0.862625,0.83475,0.86825,0.863683,0.848970,0.851500
11,is_casecontrol,log,1,elasticnet,1.623777e-06,0.84975,0.87575,0.872433,0.860942,0.862750,0.83525,0.87175,0.866892,0.850777,0.853500
12,is_casecontrol,modified_huber,1,l2,1.000000e-10,0.86450,0.84425,0.847341,0.855835,0.854375,0.85175,0.83425,0.837101,0.844362,0.843000
13,is_casecontrol,squared_hinge,1,l2,1.274275e-08,0.83950,0.86700,0.863239,0.851204,0.853250,0.82775,0.85850,0.854011,0.840675,0.843125
14,is_casecontrol,perceptron,1,elasticnet,2.069138e-09,0.86850,0.84725,0.850428,0.859369,0.857875,0.85825,0.82850,0.833455,0.845671,0.843375
15,is_cohort,hinge,1,l2,1.000000e-05,0.84325,0.83800,0.838846,0.841042,0.840625,0.85375,0.83675,0.839479,0.846554,0.845250
16,is_cohort,log,1,l2,2.976351e-06,0.86000,0.83475,0.838820,0.849278,0.847375,0.86450,0.83100,0.836478,0.850258,0.847750
17,is_cohort,modified_huber,1,l2,2.069138e-09,0.86550,0.81000,0.819991,0.842131,0.837750,0.86375,0.81400,0.822815,0.842786,0.838875
18,is_cohort,squared_hinge,1,l1,6.951928e-09,0.86600,0.80600,0.816981,0.840777,0.836000,0.87100,0.81275,0.823057,0.846350,0.841875
19,is_cohort,perceptron,1,elasticnet,1.274275e-08,0.86250,0.81475,0.823193,0.842388,0.838625,0.86075,0.81650,0.824276,0.842118,0.838625
20,is_guideline,hinge,1,elasticnet,1.000000e-05,0.95675,0.96200,0.961799,0.959268,0.959375,0.95525,0.96375,0.963439,0.959327,0.959500
21,is_guideline,log,1,l1,5.455595e-06,0.95575,0.96525,0.964917,0.960311,0.960500,0.95325,0.96300,0.962636,0.957920,0.958125
22,is_guideline,modified_huber,1,l1,6.158482e-10,0.95500,0.94525,0.945779,0.950367,0.950125,0.95675,0.94700,0.947512,0.952108,0.951875
23,is_guideline,squared_hinge,1,elasticnet,2.335721e-08,0.94425,0.96275,0.962048,0.953066,0.953500,0.94700,0.96300,0.962398,0.954637,0.955000
24,is_guideline,perceptron,1,elasticnet,4.281332e-08,0.95075,0.95850,0.958176,0.954448,0.954625,0.94700,0.95900,0.958502,0.952716,0.953000

In [12]:
results_gbdt_pd = pd.read_json('results_titles_abstracts_gbdt.json')

In [13]:
results_gbdt_pd

,ptype,model_type,neg_to_pos_ratio,gamma,reg_alpha,reg_lambda,colsample_bytree,min_child_weight,recall_val,spec_val,precision_val_even,f1_val_even,accuracy_val,recall_test,spec_test,precision_test_even,f1_test_even,accuracy_test
0,is_rct,gbdt,1,0.884925,45.227289,325.330331,0.798950,1.959829,0.91075,0.93300,0.931475,0.920996,0.921875,0.91450,0.92825,0.927250,0.920831,0.921375
1,is_sr,gbdt,1,0.893724,1.808479,373.592077,0.955134,2.773576,0.98350,0.99225,0.992182,0.987822,0.987875,0.98750,0.99300,0.992961,0.990223,0.990250
2,is_casecontrol,gbdt,1,0.000000,0.000000,714.816981,1.000000,0.000000,0.87175,0.87125,0.871314,0.871532,0.871500,0.87000,0.86675,0.867182,0.868589,0.868375
3,is_cohort,gbdt,1,0.000000,0.000000,176.775206,1.000000,0.000000,0.87600,0.82825,0.836077,0.855573,0.852125,0.87675,0.82500,0.833611,0.854636,0.850875
4,is_guideline,gbdt,1,0.000000,0.000000,728.440006,0.500000,0.000000,0.96100,0.96375,0.963650,0.962323,0.962375,0.95975,0.96125,0.961192,0.960470,0.960500