In [2]:
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
results_titles_abstracts = pd.read_json('results_titles_abstracts_linear_corrected.json')
results_abstracts = pd.read_json('results_abstracts_linear_corrected.json')

In [4]:
results_titles_abstracts[results_titles_abstracts['ptype'] == 'is_guideline']

,ptype,model_type,neg_to_pos_ratio,best_penalty,best_alpha,recall_val,precision_val,f1_val,accuracy_val,recall_test,precision_test,f1_test,accuracy_test
25,is_guideline,hinge,1,elasticnet,1.000000e-05,0.957826,0.135467,0.237363,0.972004,0.961314,0.134278,0.235641,0.971633
26,is_guideline,log,1,elasticnet,2.976400e-06,0.960260,0.132113,0.232271,0.971126,0.962044,0.129750,0.228661,0.970478
27,is_guideline,modified_huber,1,elasticnet,2.100000e-09,0.937551,0.101146,0.182594,0.961819,0.940146,0.099390,0.179775,0.960979
28,is_guideline,squared_hinge,1,l1,2.340000e-08,0.942417,0.073904,0.137061,0.946023,0.957664,0.074440,0.138142,0.945647
29,is_guideline,perceptron,1,l1,8.859000e-07,0.932685,0.119630,0.212060,0.968474,0.939416,0.118793,0.210914,0.968027

In [9]:
results_titles_abstracts[results_titles_abstracts['ptype'] == 'is_casecontrol']

,ptype,model_type,neg_to_pos_ratio,best_penalty,best_alpha,recall_val,precision_val,f1_val,accuracy_val,recall_test,precision_test,f1_test,accuracy_test
10,is_casecontrol,hinge,1,l1,1.000000e-05,0.852786,0.110813,0.196139,0.892416,0.856711,0.111211,0.196866,0.892410
11,is_casecontrol,log,1,elasticnet,2.976400e-06,0.842699,0.110211,0.194928,0.892867,0.854982,0.112361,0.198619,0.893807
12,is_casecontrol,modified_huber,1,elasticnet,8.859000e-07,0.781460,0.076649,0.139606,0.851751,0.779987,0.077247,0.140573,0.853203
13,is_casecontrol,squared_hinge,1,l1,1.100000e-09,0.830211,0.073438,0.134939,0.836171,0.840069,0.074345,0.136602,0.836547
14,is_casecontrol,perceptron,1,l2,2.000000e-10,0.834534,0.071216,0.131234,0.829943,0.844392,0.072197,0.133020,0.830583

In [10]:
results_abstracts[results_abstracts['ptype'] == 'is_sr']

,ptype,model_type,neg_to_pos_ratio,best_penalty,best_alpha,recall_val,precision_val,f1_val,accuracy_val,recall_test,precision_test,f1_test,accuracy_test
30,is_sr,hinge,1,l1,2.976400e-06,0.979041,0.555626,0.708924,0.979139,0.980257,0.550611,0.705143,0.978729
31,is_sr,log,1,l1,5.455600e-06,0.968562,0.644178,0.773747,0.985302,0.972334,0.641021,0.772659,0.985154
32,is_sr,modified_huber,1,elasticnet,1.000000e-05,0.975129,0.529675,0.686470,0.976888,0.980382,0.531316,0.689149,0.977052
33,is_sr,squared_hinge,1,l2,4.833000e-07,0.968003,0.369375,0.534712,0.956288,0.973340,0.370388,0.536587,0.956378
34,is_sr,perceptron,1,l2,2.000000e-10,0.963812,0.451410,0.614850,0.968669,0.966424,0.454169,0.617939,0.968992